### ISSUE TITLE
Problems with variables in tasks

### ISSUE THREAD

**Issue by bart84ek** [bilus/oya#25]
It not the first time when i'm having problems with defining varialbes inside tasks.
Now i see that it's impossible to define scripts with {print} 

```
docker ps | grep oya-example-front | awk '{print $1}' | xargs docker stop
```

**Comment by bilus** [comment]
`docker ps | grep oya-example-front | awk '{print $$1}' | xargs docker stop` should work.

**Comment by bilus** [comment]
One option would be to change it so oya variables are accessed using $$ while bash variables - via single $, e.g. `$$BasePath`. This would make it more intuitive for the newcomers.

**Comment by bart84ek** [comment]
resolved ;)
